### PR TITLE
Added --on-before-fail and --on-after-fail runtime options

### PR DESCRIPTION
**Pull request by jamescun**
New runtime options:

  - `--on-before-fail`: determines the job behaviour on a before check failing.
    - `continue` continue with execution of the job
    - `skip` skip and start the next job (default)
    - `end` end the current buddha run and exit
  - `--on-after-fail`: determines the run behavior on an after check failing.
    - `continue` continue with execution of next job
    - `end` end the current buddha run and exit (default)

### CODE REVIEW

**Comment by jamescun** [comment]
@mdpye does this satisfy your use case?

**Comment by mdpye** [comment]
I think so, yes. Although I was going to differentiate in the config between before checks which determine the health of the thing to be changed, and those which determine the necessity of the change. But we don't have any of the former yet, so perhaps that's premature.

**Comment by jamescun** [comment]
@mdpye I think you might be right, a option in the config file might make more sense, particularly if you are running multiple jobs.

@zimbatm any thoughts?

**Comment by zimbatm** [comment]
I like the flexibility of the proposed change as a plumbing.

In terms of UX in my daily activity I have two main needs:

* Apply the stronghold changes to the machine in the right order and idempotent way. This is the 80% and might be worth optimising to just `buddha`

* Forcefully restart processes when they get stuck. For example the socket processes when the sockjs-bridge doesn't catch them. Maybe something like `buddha restart <group-name | all>`. It would still abort if the post-checks are failing, maybe add a `--force` to be even more brutal.

**Comment by jamescun** [comment]
@mdpye changes look good, merge?

**Pull request merged**
