### PR TITLE
Retry necessity checks which fail with an unknown error

### PR DESCRIPTION
**Pull request by mdpye**
Returning the last error value as the result if we run out of retries
without getting a non-error response

### CODE REVIEW

**Comment by mdpye** [comment]
cc @WillSewell

**Comment by WillSewell** [comment]
In that case I'm assuming we also want to retry health checks on unexpected failures?

**Comment by mdpye** [comment]
I guess we probably do. Although it's less important, because health-checks are generally repeated, where necessity checks are run only once

**Comment by mdpye** [comment]
Oh, but we explicitly halt immediately. Yes, I'll add it to the PR

**Comment by WillSewell** [comment]
Should probably remove the `"do not retry"` from the comment.

Also it would be nice to have the `Check %d/%d: %s: ` prefixing all loggings of the necessity check for consistency.

Looks good otherwise.

**Comment by mdpye** [comment]
I've logged the actual failure, but not the introductory numbering, as we only *expect* to run the necessity check once.

**Pull request merged**
